# Generated by Django 3.2.15 on 2022-11-07 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ePrescribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='med_practice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ePrescribe.medpractice', to_field='reference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='practice_number',
            field=models.CharField(max_length=20),
        ),
    ]
